"""Mappings for nested Elastic Common Schema JSON flattened by Parseable."""

from sigma.pipelines.common import generate_windows_logsource_items
from sigma.processing.conditions import (
    FieldNameProcessingItemAppliedCondition,
    IncludeFieldCondition,
    LogsourceCondition,
)
from sigma.processing.pipeline import ProcessingItem, ProcessingPipeline
from sigma.processing.transformations import (
    AddFieldnamePrefixTransformation,
    FieldMappingTransformation,
)

ECS_WINDOWS_FIELDS = {
    "EventID": "event_code",
    "Channel": "winlog_channel",
    "Provider_Name": "winlog_provider_name",
    "Computer": "host_name",
    "ComputerName": "winlog_computer_name",
    "ProcessGuid": "process_entity_id",
    "ProcessId": "process_pid",
    "Image": "process_executable",
    "CommandLine": "process_command_line",
    "CurrentDirectory": "process_working_directory",
    "ParentProcessGuid": "process_parent_entity_id",
    "ParentProcessId": "process_parent_pid",
    "ParentImage": "process_parent_executable",
    "ParentCommandLine": "process_parent_command_line",
    "FileVersion": "process_pe_file_version",
    "Description": "process_pe_description",
    "Product": "process_pe_product",
    "Company": "process_pe_company",
    "OriginalFileName": "process_pe_original_file_name",
    "TargetFilename": "file_path",
    "FileName": "file_path",
    "ImageLoaded": "file_path",
    "Device": "file_path",
    "Signed": "file_code_signature_signed",
    "Signature": "file_code_signature_subject_name",
    "SignatureStatus": "file_code_signature_status",
    "Imphash": "file_pe_imphash",
    "SourceIp": "source_ip",
    "SourceHostname": "source_domain",
    "SourcePort": "source_port",
    "SourceAddress": "source_ip",
    "ClientAddress": "source_ip",
    "ClientName": "source_domain",
    "IpAddress": "source_ip",
    "IpPort": "source_port",
    "WorkstationName": "source_domain",
    "DestinationIp": "destination_ip",
    "DestinationHostname": "destination_domain",
    "DestinationPort": "destination_port",
    "DestinationPortName": "network_protocol",
    "DestinationAddress": "destination_ip",
    "DestAddress": "destination_ip",
    "DestPort": "destination_port",
    "Protocol": "network_transport",
    "SourceProcessGuid": "process_entity_id",
    "SourceProcessId": "process_pid",
    "SourceImage": "process_executable",
    "SourceThreadId": "process_thread_id",
    "TargetObject": "registry_path",
    "PipeName": "file_name",
    "Destination": "process_executable",
    "QueryName": "dns_question_name",
    "QueryStatus": "sysmon_dns_status",
    "IsExecutable": "sysmon_file_is_executable",
    "Archived": "sysmon_file_archived",
    "AccountDomain": "user_domain",
    "AccountName": "user_name",
    "SubjectDomainName": "user_domain",
    "SubjectUserName": "user_name",
    "SubjectUserSid": "user_id",
    "TargetDomainName": "user_target_domain",
    "TargetUserName": "user_target_name",
    "TargetUserSid": "user_target_id",
    "User": "user_name",
    "NewProcessId": "process_pid",
    "NewProcessName": "process_executable",
    "ParentProcessName": "process_parent_executable",
    "ProcessName": "process_executable",
    "ScriptName": "file_path",
    "SequenceNumber": "event_sequence",
    "HostApplication": "process_command_line",
    "HostId": "process_entity_id",
    "HostName": "process_title",
    "CommandName": "powershell_command_name",
    "CommandPath": "powershell_command_path",
    "CommandType": "powershell_command_type",
    "ScriptBlockText": "powershell_file_script_block_text",
    "ScriptBlockId": "powershell_file_script_block_id",
    "Payload": "powershell_file_script_block_text",
}


def parseable_ecs_pipeline() -> ProcessingPipeline:
    """Map Windows Sigma fields to Parseable-flattened ECS columns."""
    return ProcessingPipeline(
        name="Parseable flattened ECS Windows mappings",
        priority=20,
        allowed_backends=frozenset({"parseable"}),
        items=generate_windows_logsource_items("winlog_channel", "{source}")
        + [
            ProcessingItem(
                identifier="parseable_ecs_windows_fields",
                transformation=FieldMappingTransformation(ECS_WINDOWS_FIELDS),
                rule_conditions=[LogsourceCondition(product="windows")],
            ),
            ProcessingItem(
                identifier="parseable_ecs_windows_event_data",
                transformation=AddFieldnamePrefixTransformation("winlog_event_data_"),
                field_name_conditions=[
                    FieldNameProcessingItemAppliedCondition("parseable_ecs_windows_fields"),
                    IncludeFieldCondition(fields=[r"\w+[._]\w+"], mode="re"),
                ],
                field_name_condition_negation=True,
                field_name_condition_linking=any,
                rule_conditions=[LogsourceCondition(product="windows")],
            ),
        ],
    )
